sudo: false
language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
  - master
notifications:
  email: false
node_js:
  - '4'
  - '5'
  - '6'
before_install:
  - npm i -g npm@^3.9.5
before_script:
  - npm prune
script:
  - npm run build
